apiVersion: v1
kind: Service
metadata:
  name: pihole
  annotations:
    external-dns.alpha.kubernetes.io/hostname: pihole.christianlowe.com
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: pihole
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
spec:
  selector:
    matchLabels:
      app: pihole
  replicas: 1
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
        - name: pihole
          image: pihole/pihole
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-dns
spec:
  type: LoadBalancer
  ports:
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
  selector:
    app: pihole
