services:
  clowe-drf:
    container_name: clowe-drf
    volumes:
      - "../../../drf:/usr/src/app"
      - "./logs:/var/log/app"
    build:
      context: ../../../drf
      dockerfile: ../docker/drf/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ../env.sample
  db:
    container_name: clowe-drf-db
    image: postgres:17.4-alpine3.21
    ports:
      - "5432:5432"
    env_file:
      - ../env.sample
