services:
  clowe-drf:
    container_name: clowe-drf
    volumes:
      - "../../../drf:/usr/src/app"
    build:
      context: ../../../drf
      dockerfile: ../docker/drf/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: password
      POSTGRES_DB: clowe-app
      POSTGRES_HOST: clowe-drf-db
      APPLE_APP_AUDIENCE: com.christianlowe.app
  db:
    container_name: clowe-drf-db
    image: postgres:17.4-alpine3.21
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: password
      POSTGRES_DB: clowe-app
