---
- name: Setup User
  hosts: clowe-app-webservers
  become: true

  tasks:
    - name: Ensure group exists
      ansible.builtin.group:
        name: "{{ item }}"
        state: present
      with_items:
        - clowe-app
        - docker

    - name: Add the user 'clowe-app' with a group of clowe-app and docker
      ansible.builtin.user:
        name: clowe-app
        comment: clowe-app user for running docker
        groups:
          - clowe-app
          - docker
