apiVersion: v1
kind: Service
metadata:
  name: sampleservice
  annotations:
    external-dns.alpha.kubernetes.io/hostname: test-service.christianlowe.com
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: myapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myserver
          image: nginx
          imagePullPolicy: IfNotPresent
