services:
  clowe-app:
    container_name: clowe-app
    volumes:
      - "../backend:/usr/src/app"
      - "clowe-app-logs:/var/log/app"
    build:
      context: ../
      dockerfile: docker/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: password
      POSTGRES_DB: clowe-app
    networks:
      - default
      - grafana-net
      - clowe-net
  db:
    container_name: clowe-app-db
    image: postgres:17.4-alpine3.21
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: password
      POSTGRES_DB: clowe-app
    volumes:
      - "clowe-app-db-data:/var/lib/postgresql/data"
  fluentbit:
    container_name: clowe-fluent-bit
    image: fluent/fluent-bit
    volumes:
      - ./fluentbit-backend.conf:/fluent-bit/etc/fluent-bit.conf
      - ./fluentbit-parsers.conf:/fluent-bit/etc/custom_parsers.conf
      - clowe-app-logs:/var/log/app
    networks:
      - opensearch-net
      - grafana-net

volumes:
  clowe-app-db-data:
    name: clowe-app-db-data
    external: false
  clowe-app-logs:
    name: clowe-app-logs
    external: false

networks:
  opensearch-net:
    external: true
  grafana-net:
    external: true
  clowe-net:
    name: clowe-net
    external: false
