services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/loki-config.yaml
    command: -config.file=/etc/loki/loki-config.yaml
    networks:
      - grafana-net

  prometheus:
    image: prom/prometheus:v2.46.0
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - grafana-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - "grafana-data:/var/lib/grafana"
    ports:
      - "3000:3000"
    networks:
      - grafana-net

volumes:
  grafana-data:
    name: grafana-data

networks:
  grafana-net:
    name: grafana-net
    external: false
