services:
  clowe-app:
    container_name: clowe-app
    volumes:
      - "../../drf:/usr/src/app"
      - "clowe-app-logs:/var/log/app"
    build:
      context: ../../drf
      dockerfile: ../docker/drf/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: password
      POSTGRES_DB: clowe-app
    networks:
      - default
      - clowe-net
  db:
    container_name: clowe-app-db
    image: postgres:17.4-alpine3.21
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: password
      POSTGRES_DB: clowe-app
    volumes:
      - "clowe-app-db-data:/var/lib/postgresql/data"

volumes:
  clowe-app-db-data:
    name: clowe-app-db-data
    external: false
  clowe-app-logs:
    name: clowe-app-logs
    external: false

networks:
  clowe-net:
    name: clowe-net
    external: false
