services:
  clowe-drf:
    image: imchristianlowe/clowe-drf:latest
    container_name: clowe-drf
    pull_policy: always
    volumes:
      - "clowe-app-logs:/var/log/app"
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - /etc/clowe-app/env
    networks:
      - default
      - clowe-net
    depends_on:
      - db
  db:
    image: postgres:17.4-alpine3.21
    container_name: clowe-drf-db
    env_file:
      - /etc/clowe-app/env
    volumes:
      - "clowe-app-db-data:/var/lib/postgresql"

volumes:
  clowe-app-db-data:
    name: clowe-app-db-data
    external: false
  clowe-app-logs:
    name: clowe-app-logs
    external: false

networks:
  clowe-net:
    name: clowe-net
    external: false
