---
- name: Install App As Service
  hosts: clowe-app-webservers
  become: true

  tasks:
    - name: Ensure group exists
      ansible.builtin.group:
        name: "{{ item }}"
        state: present
      with_items:
        - clowe-app
        - docker

    - name: Add the user 'clowe-app' with a group of clowe-app and docker
      ansible.builtin.user:
        name: clowe-app
        comment: clowe-app user for running docker
        groups:
          - clowe-app
          - docker

    - name: Copy docker files over
      ansible.builtin.copy:
        src: ../docker
        dest: /opt/clowe-app
        owner: clowe-app
        group: clowe-app
        mode: u+rwx,g-wx,o-rwx

    - name: Copy DRF files over
      ansible.builtin.copy:
        src: ../drf
        dest: /opt/clowe-app
        owner: clowe-app
        group: clowe-app
        mode: u+rw,g-wx,o-rwx

    - name: Build DRF Image
      community.docker.docker_image:
        name: clowe-drf
        build:
          dockerfile: /opt/clowe-app/docker/drf/Dockerfile
          path: /opt/clowe-app/drf
        source: build
        force_source: true # forces a rebuild if the image name:tag already exists
      become_user: clowe-app

    - name: Stop existing services
      community.docker.docker_compose_v2:
        project_src: /opt/clowe-app/docker/drf/prod
        files:
          - docker-compose.yml
        state: stopped
      become_user: clowe-app

    - name: Create and start services
      community.docker.docker_compose_v2:
        project_src: /opt/clowe-app/docker/drf/prod
        files:
          - docker-compose.yml
        build: always
        state: present
      become_user: clowe-app

    - name: run migrations
      ansible.builtin.shell: docker compose exec -it clowe-drf python manage.py migrate
      args:
        chdir: /opt/clowe-app/docker/drf/prod
      become_user: clowe-app

    - name: Start Cloudflared
      community.docker.docker_compose_v2:
        project_src: /opt/clowe-app/docker
        files:
          - cloudflare.yml
        state: present
      become_user: clowe-app
      when: run_cloudflare_container is defined and run_cloudflare_container | bool
      environment:
        TUNNEL_TOKEN: "{{ tunnel_token }}"
