- name: Restore Docker Volume from DB Backup
  hosts: clowe-app-webservers
  become: true

  tasks:
    - name: Restore Backup from S3
      ansible.builtin.shell: |
        result=$(aws sts assume-role --role-arn ${AWS_IAM_ROLE} --role-session-name s3-backup)
        export AWS_ACCESS_KEY_ID=$(echo $result | jq '.Credentials.AccessKeyId' -r)
        export AWS_SECRET_ACCESS_KEY=$(echo $result | jq '.Credentials.SecretAccessKey' -r)
        export AWS_SESSION_TOKEN=$(echo $result | jq '.Credentials.SessionToken' -r)
        aws s3 cp ${BACKUP_FILE} /tmp/restore.sql
        cat /tmp/restore.sql | docker compose exec db psql -U postgres
        rm /tmp/restore.sql
      environment:
        AWS_IAM_ROLE: "{{ AWS_IAM_ROLE }}"
        AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ AWS_SECRET_ACCESS_KEY }}"
        BACKUP_FILE: "{{ BACKUP_FILE }}"
      args:
        chdir: /opt/clowe-app/docker/drf/prod
