services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    ports:
      - "8085:8080"
    #    volumes:
    #      - ./config/keycloak/realms:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: ["start-dev"]
