name: Publish docs via GitHub Pages
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      #      - name: Run image
      #        uses: abatilo/actions-poetry@v3
      #        with:
      #          poetry-version: 2.0.1
      #      - name: Install Dependencies
      #        run: |
      #          poetry add mkdocs
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - run: |
          mkdocs gh-deploy --force
